# Generated by Django 3.2.8 on 2021-10-07 04:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_expenserecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
