# Generated by Django 3.2.8 on 2021-10-07 05:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='avatar',
            field=models.ImageField(null=True, upload_to=core.models.record_image_file_path),
        ),
    ]
